colors: true

prepare-commit-msg:
  commands:
    commitlint:
      run: yarn commitlint --edit $1

pre-commit:
  parallel: true
  commands:
    prettier:
      glob: '*.{js,ts,jsx,tsx,astro,md}'
      run: yarn format {staged_files} && git update-index --again
      stage_fixed: true
    eslint:
      glob: '*.{js,ts,jsx,tsx,astro,md}'
      run: yarn lint:fix {staged_files} && git update-index --again
      stage_fixed: true
    test:
      run: yarn test:ci {staged_files} && git update-index --again

pre-push:
  parallel: true
  commands:
    typescript:
      run: yarn typecheck
    build:
      run: yarn build
#    packages-audit:
#      tags: frontend security
#      run: yarn audit
