name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      #  config_actions:
      - name: Checkout Repository
        uses: actions/checkout@v3

      #  setup_node:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      #  install_dependencies:
      - name: Install Dependencies
        run: yarn install

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Run Playwright tests
        run: yarn playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
